name:                trade-leaf-websockets
version:             0.1.0.0
github:              "githubuser/trade-leaf-websockets"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/trade-leaf-websockets#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - split

executables:
  trade-leaf-websockets-exe:
    main:                Server.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trade-leaf-websockets
    - websockets
    - mtl
    - attoparsec
    - base
    - base64-bytestring
    - binary
    - blaze-builder
    - bytestring
    - case-insensitive
    - containers
    - network
    - random
    - SHA
    - text
    - entropy

tests:
  trade-leaf-websockets-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trade-leaf-websockets
    - hspec
